version: '2'
services:
    dev:
        image: "${MY_IMAGE}"
        hostname: dev
        # see http://blog.johngoulah.com/2016/03/running-strace-in-docker/
        security_opt:
          - seccomp:unconfined
        volumes: 
          - ${MY_HOME}:/home/dev
          - ${HOME}/applications:/home/dev/applications
          - ${HOME}/.gnupg:/home/dev/.gnupg
          - /tmp/.X11-unix:/tmp/.X11-unix:rw
          - /usr/bin/docker:/bin/docker:rw
          - /var/run/docker.sock:/run/docker.sock:rw
          - ${SSH_AUTH_SOCK}:/ssh-agent
        environment:
          - DISPLAY=${DISPLAY}
          - SSH_AUTH_SOCK=/ssh-agent

    redis:
        image: redis:4.0.1-alpine
        ports:
          - "6379:6379"

    xemx:
        image: icij/xemx
        dns: 172.30.0.2
        ports:
          - "3001:3001"
        volumes:
          - ./secrets.yml:/usr/src/xemx/config/secrets.yml
        environment:
          - "XEMX_HOST=xemx"

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
        environment:
          - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
          - "discovery.type=single-node"
          - "cluster.name=datashare"
          - "http.cors.enabled=true"
          - "http.cors.allow-origin=*"
          - "http.cors.allow-methods=OPTIONS, HEAD, GET, POST, PUT, DELETE"
        ports:
          - "9200:9200"
